# Generated by Django 5.1.4 on 2024-12-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.99, max_digits=8),
            preserve_default=False,
        ),
    ]
