# Generated by Django 5.1.4 on 2024-12-15 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
